affiliation_editor_disabled I'm owner of this room. This command is disabled for security purposes.
alias_cleared cleared
alias_deleted deleted
alias_empty alias list is empty
alias_no_access not allowed
alias_not_allowed not allowed
alias_not_found alias not found
alias_saved saved
alias_saved_with_access alias saved (required level: %s, alias grants: %s)
censor censor from %s\nnick: %s(%s)\ncensor: %s\n%s 
chatlog_banned_reason %s was banned: %s
chatlog_banned %s was banned
chatlog_changed_nick changes nick to %s
chatlog_change_subject %s has set the subject: %s
chatlog_joined joins the room
chatlog_kicked_reason %s was kicked: %s
chatlog_kicked %s was kicked
chatlog_leaved leaves the room
chatlog_leaved_reason leaves the room: %s
chatlog_subject Subject: %s
cleaned cleaned
current_lang Current language is English (en)
disco_empty disco list is empty
disco_error can't query
ERROR During processing your message, an exception has been catched. If you're admin, read %s for more information.
from_me me
from_you you
get_msglimit %s
globmsg_sent sent to %s rooms
google? google?
google_history_notfound history not found for 'next'
google_no_results no results
google_result %s\n%s (%s)
google_results %s\n(%s results)
groupchats currently i'm spending time in %s\n(total count: %s)
help_categories Categories: %s\nto get command list, type 'help category', e.g. 'help basic'
help_category %s.\nTo get help, you need type '.help command', e.g. '.help test'
help_not_found not found (%s)
help_other_languages unfortunabelly help for '%s' not implemented yet in language '%s'; use %s, to see help in other languages
help_saved ok
help_show This command placed in categories: %s\n\n%s
idle_error can't query
idle_result %s`s idle is %s
info %s %s's uptime is %s\nload average: %s stanza/sec, stanza length %s
invalid_error_stanza can't understand server response: %s
invalid_syntax_default Invalid syntax
invalid_syntax Syntax:\n%s
join_already_there I'm already in that room... if not, you should to ask my admin to give me command ".rejoin"
joined Joined '%s'
join_failed can't join to %s (with nick %s)
join_slash invalid room or nick: "/" is not allowed
join_success joined to %s with nick %s
lang_changed Language successfully changed
lang_list Available languages: %s
lang_msg_saved saved
lang_not_found Language '%s' not found. Use .lang_list to see list of available languages.
lang_other_languages unfortunabelly help for '%s' not implemented yet in language '%s'; use %s instead
lang_self English (en)
leaved Leaved '%s'
log.header <html><head><title>freq log</title></head><body>\n
log.record <p><i><font color="#999999">[%d.%m.%y %H:%M:%S]</font></i> %%s</p>\n
moderate_error can't
moderate_not_found who?
moderate_ok ok
msglimit_saved saved
muc_only this command available only in conference
muc_whois %s/%s\n%s(%s)\njoined %s\naccess level: %s
nick_updated ok
nick_update ok
noisy_already_off "noisy" mode is not enabled
noisy_already_on "noisy" mode already turned on
noisy_ban %s banned... %s
noisy_join %s: hello
noisy_kick bustards! the killed %s?? %s?
noisy_leave %s: you leave? :( (%s)
noisy_rename %s: change nick??
not_allowed Not allowed.
ok O'key
ping_error can`t ping
pong pong from %s %s
pyexec.ok Successful!
rewrite_cycle ERROR: recursion level more than %s
rewrite_too_many_commands Too many commands! need to be <%s
see_private see private
stats_error unknown
stats_result Stats for %s\nTotal: %s users\nOnline: %s users
status_updated ok
status_update ok
status_whom who?
test.passed passed
time_error unknown
uptime_error can't query
uptime_result %s's uptime is %s
vcard_error failed to fetch vcard
version_error failed
version_result_jid on %s %s %s %s
version_result_nick %s use %s %s %s
version_result_self %s %s %s
version_result_your you use %s %s %s
whom? who?
update_info my revision: %s available revision: %s
wtf_empty What to look?
wtf_not_found Has found nothing
dfn_empty What to write?
dfn_save Has saved
dfn_remove Has deleted
dfn_failed Has not found in a database
wtf_result I know that %s:\n%s
wtfnames_result In database of this conference I see
wtfnames_result I see this:\n %s (in total %s)
wtfnames_empty The database is empty
wtfsearch_result Coincidences are found in: %s
wtfsearch_error not found
wtfsearch_not_parameters what to search?
