access_added сохранил
access_add_invalid_syntax синтаксис: .access_add jid access
access_cleared список очищен
access_del_404 нет такой записи
access_deleted удалено
access_list_empty список пуст
added добавлено
alias_cleared очищено
alias_deleted удалил
alias_empty нет ни одного алиаса
alias_no_access у вас недостаточно прав, чтобы поставить такой высокий уровень выполнения алиаса
alias_not_allowed у вас недостаточно прав для выполнения этого алиаса
alias_not_found нет такого алиаса
alias_security возможно, этот алиас небезопасен
alias_saved_with_access алиас сохранён (уровень доступа к алиасу: %s, алиас будет выполняться с уровнем доступа %s)
alias_saved сохранил
alist_add_nojid не вижу его jid..
blacklist_deleted удалено
blacklist_not_found нет такой комнаты в списке
censor_already_subscribed вы уже подписаны
censor_list_empty список пуст
censor_nojid не вижу вашего jid..
censor_not_subscribed вы не подписаны на цензор из этой комнаты
censor_subscribed вы подписались на цензор из %s
censor_unsubscribed вы отписались от цензора из %s
censor цензор из %s\nник: %s(%s)\nцензор: %s\n%s
cerberus_invalid_mode нет такого режима. Прочитай справку по команде
chatlog_banned_reason запретили входить в конференцию: %s
chatlog_banned запретили входить в конференцию
chatlog_changed_nick сменил ник на %s
chatlog_change_subject %s установил(а) тему: %s
chatlog_joined зашёл в конференцию
chatlog_kicked_reason выгнали из конференции: %s
chatlog_kicked выгнали из конференции
chatlog_leaved_reason вышел из конференции: %s
chatlog_leaved вышел из конференции
chatlogs_already_disabled чатлоги уже отключены
chatlogs_already_enabled чатлоги уже включены
chatlogs_disabled логирование отключено
chatlogs_enabled логирование включено
chatlog_subject Тема: %s
cleaned зачистка выполнена
cleared очищено
current_lang текущий язык русский (ru)
deleted удалено
disco_empty список пуст
disco_error не получилось
ERROR Произошла ошибка при обработке вашего сообщения. По возможности, сообщите об этом админу бота. Если вы админ, то почитайте %s для более подробной информации
e_feature-not-implemented %s не поддерживает такую фичу
e_forbidden %s не разрешает запрашивать такую информацию
e_gone %s там больше не живёт
e_internal-server-error %s глючит
e_jid-malformed некорректный jid: %s
e_recipient-unavailable %s временно недоступен
e_remote-server-not-found %s не существует
e_remote-server-timeout %s не отвечает (висит?)
e_service-unavailable %s не предоставляет такого сервиса
failed не получилось
from_me меня
from_you тебя
get_msglimit %s
globmsg_sent сообщение отправлено в %s конференций
google_error гугль сломался
google_history_notfound нет истории поиска для 'next'
google_no_results не нашел
google_result %s\n%s (%s)
google_results %s\n(всего %s результатов)
google? чо искать?
groupchats сейчас я сижу в %s\n(всего %s конференций)
he_is_here %s и ныне тут
help_categories Категории: %s\nчтобы получить список команд в категории напиши 'help категория', например 'help basic'
help_category Команды в этой категории: %s.\nДля справки по команде пишите '.help команда', например '.help test'
help_not_found не найдено (%s)
help_other_languages к сожалению справка по '%s' пока не написана на языке '%s'; вы можете использовать вместо этого %s
help_saved ok\n
help_show Категории: %s\n\n%s
i_am_not_there меня нет там
idle_error не получилось
idle_result %s молчит %s
incoming_message %s назад %s передал вам сообщение из комнаты %s:\n%s
invalid_error_stanza сервер прислал станзу ошибки, которую я не могу разобрать: %s
i_never_see_him я никогда тут не видел %s
info я, %s %s, работаю без остановок %s\nНагрузка: %s станз в секунду, средняя длина станзы %s байт.
invalid_encoding неправильная кодировка!
invalid_nick_or_jid неправильный jid или ник
invalid_regexp ошибка в регулярном выражении
invalid_syntax_default неправильный синтаксис
invalid_syntax синтаксис:\n%s
join_already_there я уже сижу в той комнате... если это не так, то попросите админа бота дать команду .rejoin
join_failed не получилось зайти в %s (c ником %s)
join_not_permitted_reason админ запретил приглашать бота в %s\nпричина: %s
join_not_permitted админ запретил приглашать бота в %s
join_slash в имени конфы и нике не должно быть /
join_success зашёл в конфу %s с ником %s
join_try пытаюсь зайти в <%s>...
lang_changed язык изменен
lang_list доступные языки - %s
lang_msg_saved записано
lang_not_found язык '%s' недоступен, или его не существует; используйте .lang_list для просмотра списка доступных языков.
lang_self Русский (ru)
leaved вышел из '%s'
left истекает через
list_cleared список очищен
list_empty список пуст
log.header <html><head><title>freq log</title></head><body>\n
log.record <p><i><font color="#999999">[%d.%m.%y %H:%M:%S] [PID $PID$]</font></i> %%s</p>\n
moderate_error не получилося
moderate_not_found кого?
moderate_ok ok
msg_authentication_request кто-то пытается отправить вам сообщение из %s. Если вы хотите получать сообщения из той комнаты - напишите .msg_whitelist %s, заблокировать их - .msg_blacklist %s
msg_auth_requested пользователю отправлен запрос, согласен ли он получать сообщения из этой конференции. Как только он подтвердит своё согласие - сообщение будет доставлено.
msgbox_is_full ящик получателя переполнен. Сообщение не отправлено.
msglimit_saved сохранено
msg_sent сообщение отправлено
muc_only команда доступна только в конференции
muc_access %s/%s\n%s(%s)\nзашел в конфу %s\nуровень доступа: %s
muc_whois Эта команда будет удалена в ближайшей версии. Используйте .access. %s/%s\n%s(%s)\nзашел в конфу %s\nуровень доступа: %s
nick_in_use этот ник уже используется в конференции
nick_not_found нет такого ника
nick_updated ok
nick_update ok
noisy_already_off "шумный" режим не включён
noisy_already_on "шумный" режим уже включён
noisy_ban %s зобанен: %s
noisy_join /me категорически приветствует %s
noisy_kick зачем кикнули %s?? %s?
noisy_leave %s: ты ушёл? :( (%s)
noisy_rename %s: шифруешся??
not_allowed фиг
not_found не найдено
nothing_to_delete нечего удалять
number_not_found нет такого номера
ok O'key
ping_error не получается
pong понг от %s %s
pyexec.ok выполнено
redirect_nowhere нет такого ника
restarting скоро вернусь...
rewrite_cycle превышен предел глубины рекурсии (%s уровней) при обработке вашего сообщения. Похоже на зацикливание. Такие проблемы могут возникать при неправильно настроенных алиасах.
rewrite_too_many_commands ошибка: слишком много команд, их должно быть не более %s
room_pending он ещё не подтвердил, что согласен получать сообщеня из этой конференции
saved сохранено
seen_banned_here_reason %s забанили здесь %s назад: %s
seen_banned_here %s забанили здесь %s назад
seen_kicked_here_reason %s выгнали отсюда %s назад: %s
seen_kicked_here %s выгнали отсюда %s назад
seen_was_here_reason %s был тут %s назад (%s)
seen_was_here %s был тут %s назад
see_private глянь приват
sent отправлено
some_error произошла какая-то ошибка..
stats_error хз
stats_result Статистика %s\nВсего: %s\nОнлайн: %s
status_updated ok
status_update ok
status_whom кого?
stopping выключаюсь... подожди пару секунд..
tell_without_message что передать-то?
test.passed норма
this_room_is_ignored он не хочет получать сообщения из этой комнаты
time_error хз
updated обновил
uptime_error хз
uptime_result %s работает без остановок %s
vcard_does_not_exists vCard не заполнена
vcard_error не получилось
vcard_not_found нет информации
version_error не получилось
version_result_jid на %s %s %s %s
version_result_nick %s использует %s %s %s
version_result_self я %s %s, запущен под %s
version_result_your у тебя %s %s %s
whom? кого?
www_dns_error не резолвится
www_error_reason ошибка при загрузке страницы: %s
www_error ошибка при загрузке страницы
www_timeout_error сервер не отвечает (таймаут)
update_info моя ревизия: %s доступная svn ревизия: %s
wtf_empty что смотреть то?
wtf_not_found ничего не нашёл
dfn_empty что записать то?
dfn_save запомнил
dfn_remove удалил
dfn_failed не нашёл в базе данных
wtf_result вот что я знаю про %s:\n%s
wtfnames_result в базе этой конференции я вижу следующее:\n%s (всего: %s)
wtfnames_empty база пуста
wtfsearch_result совпадения найдены в: %s
wtfsearch_error совпадений не найдено
wtfsearch_not_parameters а что искать то?
wtf_error Ошибка %s
member член
participant участник
admin админ
moderator модератор
owner владелец
visitor безголосый
bump_phrase_0 /me пользуясь моментом, передает привет %s, который тоже пользуется «Моментом».
bump_phrase_1 /me тыкнул %s носом в лужицу документации.
bump_phrase_2 %s зверски убит тупым предметом - бошкой об стену.
bump_phrase_3 /me нажрался в слаку и пошел бить %s
bump_phrase_4 %s выполнил недопустимую операцию и будет свернут!
bump_phrase_5 %s, все когда-нибудь становятся мужчинами, юноша. :)
bump_phrase_6 %s, твой мозг можно выставлять в Палате Мер и Весов, как эталон идеальной сферы.
bump_phrase_7 /me сжигает %s красными глазами.
bump_phrase_8 %s, съешь еще этих мягких французских булок, да выпей яду.
bump_phrase_9 %s потерял право ставить софт из сырцов %)
bump_phrase_10 /me предлагает %s посмотреть картинки в tcpdump'е.
bump_phrase_11 %s, come to dark side, we have cookies!
bump_phrase_12 %s, все в этом мире стоит денег или линукс.
bump_phrase_13 /me закопал %s обратно в землю рядом с FreeBSD.
bump_phrase_14 /me прошибает на слезу глядя на %s... Кровавую.
bump_phrase_15 /me поменял %s маточную плату.
bump_phrase_16 %s, ты куда свою мышку пихал, что она такая грязная?
bump_phrase_17 %s, зачем напиваться и ползать, когда можно покурить и летать?
bump_phrase_18 Компилите %s, компилите - оно заработает :)
bump_no_jid Здесь таких нет!
bump_no_nick /me желает, что бы все жили долго и счастливо.. и умерли в один день :|
bump_freq Не учи хромого ковылять!
bump_self %s, ты в своем уме?
bump_not_in_muc Данная команда работает только внутри конференции
