added додане
alias_cleared очищено
alias_deleted видалив
alias_empty немає жодного аліасу
alias_no_access у вас недостаточно прав, чтобы поставить такой высокий уровень выполнения алиаса
alias_not_allowed у вас недостаточно прав для выполнения этого алиаса
alias_not_found такий аліас не існує
alias_saved_with_access алиас сохранён (уровень доступа к алиасу: %s, алиас будет выполняться с уровнем доступа %s)
alias_saved записав
alist_add_nojid не бачу його jid..
chatlog_banned_reason %s запретили входить в конференцию: %s
chatlog_banned %s запретили входить в конференцию
chatlog_changed_nick сменил на %s
chatlog_change_subject %s установил(а) тему: %s
chatlog_joined зашёл в конференцию
chatlog_kicked_reason %s выгнали из конференции: %s
chatlog_kicked %s выгнали из конференции
chatlog_leaved_reason вышел из конференции: %s
chatlog_leaved вышел из конференции
chatlogs_already_disabled чатлоги вже відключені
chatlogs_already_enabled чатлоги вже включені
chatlog_subject Тема: %s
cleaned прибирання завершено
cleared очищене
current_lang поточна мова Українська (ua)
deleted видалене
disco_empty список пустий
disco_error хз
ERROR Произошла ошибка при обработке вашего сообщения. По возможности, сообщите об этом админу бота. Если вы админ, то прочитайте %s, для более подробного описания ошибки
from_me менe
from_you тебе
get_msglimit %s
globmsg_sent повідомлення відправлено в  %s конференцій
google_history_notfound нема історії пошуку для використання 'next'
google_no_results нічого не знайдено
google_result %s\n%s (%s)
google_results %s\n(всего %s результатов)
google? що шукати?
groupchats зараз я сижу у %s\n(всего %s конференцій)
help_categories Категорїї: %s\nщоб отримати перелік команд у категорїї, напишіть 'help категорія', наприклад 'help basic'
help_category Команди в цій категорїї: %s.\nДля допомоги пишіть '.help команда', наприклад '.help test'
help_not_found нічого не знайдено (%s)
help_other_languages на жаль допомога по команді '%s' ще не написана на мові '%s', використовуйте %s
help_saved ok
help_show Категорїї: %s\n\n%s
i_am_not_there мене немає там
idle_error хз
idle_result %s мовчить %s
info я, %s %s, працюю без зупинок %s\nНавантаження: %s станзи в секунду, середня довжина станзи %s байт.
invalid_encoding неправильне кодування!
invalid_jid_or_nick неправильний jid або ник
invalid_regexp помилка в регулярному виразі
invalid_syntax_default некоректний синтаксис
invalid_syntax синтаксис:\n%s
join_already_there я вже там, якщо це не так, то, будь ласка, попросіть адміна бота дати команду .rejoin
joined зайшов до '%s'
join_failed не вдалося зайти  в %s (під ніком %s)
join_not_permitted_reason адмін заборонив запрошувати бота в %s\nпричина: %s
join_not_permitted адмін заборонив запрошувати бота в %s
join_slash в ім'ї конфи і в ніку не повинно бути /
join_success зайшов в конфу  %s під ніком %s
lang_changed мову змінено
lang_list доступні мови - %s
lang_msg_saved записано
lang_not_found мови '%s' не існує, використовуйте .lang_list, щоб отримати перелік доступних мов.
lang_self Українська (ua)
leaved вийшов з '%s'
left закінчується через
log.header <html><head><title>freq log</title></head><body>\n
log.record <p><i><font color="#999999">[%d.%m.%y %H:%M:%S]</font></i> %%s</p>\n
moderate_error не вдалося
moderate_not_found кого??
moderate_ok ok
msglimit_saved збережено
muc_only команда доступна тільки в конференції
muc_whois %s/%s\n%s(%s)\nзайшов в конфу %s\nрівень доступу: %s
nick_not_found немає такого ника
nick_updated ok
nick_update ok
noisy_already_off "галасливий" режим не включено
noisy_already_on "галасливий" режим вже включено
noisy_ban %s зобанений: %s
noisy_join /me категорично вітає %s
noisy_kick ну навіщо кікнули %s?? %s?
noisy_leave %s: ти вже пішов? :( (%s)
noisy_rename %s: зашифрувався??
not_allowed фіґу
number_not_found немає такого номера
ok добре
ping_error не вдалося
pong понг від %s %s
pyexec.ok виконано
restarting скоро повернуся... failed не вийшло
rewrite_cycle превышен предел глубины рекурсии (%s) при обработке вашего сообщения. Похоже на зацикливание. Такие проблемы могут возникать при неправильно настроенных алиасах.
rewrite_too_many_commands ошибка: слишком много команд, надо не более %s
see_private глянь в приват
sent відправлене
stats_error хз
stats_result Статистика для %s\nЗагальна кількість: %s\nОнлайн: %s
status_updated ok
status_update ok
status_whom кого?
stopping вимикаюся... почекай пару секунд..
test.passed добре
time_error хз
uptime_error хз
uptime_result %s працює без зупинок %s
vcard_error не получилось
version_error не вийшло
version_result_jid на %s %s %s %s
version_result_nick %s використовує %s %s %s
version_result_self я %s %s, запущений під %s
version_result_your в тебе %s %s %s
whom? кого??
www_dns_error не резолвітся
www_error_reason помилка при завантаженні сторінки: %s
www_error помилка при завантаженні сторінки
www_timeout_error сервер не відповідає (таймаут)
update_info моя ревізія: %s доступна ревізія в svn: %s
wtf_empty і що ти хочеш подивитись?
wtf_not_found нічогісінько не знайдено
dfn_empty що ж записати то?
dfn_save зберіг
dfn_remove знищив
dfn_failed не знайшов у базі даних
wtf_result ось що я знаю про %s:\n%s
wtfnames_result у базі цієї конференції я бачу наступне:\n%s (всього: %s)
wtfnames_empty база порожня
wtfsearch_result знайдені співпадання у: %s
wtfsearch_error співпадання не знайдені
wtfsearch_not_parameters а що шукати то?
